
version: '3.3'
services:
  telegraf:
    image: telegraf:1.4-alpine
    command: -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
    restart: always
    container_name: ${CONTAINER_NAMESPACE}telegraf
    hostname: telegraf
    volumes:
      - ./volumes/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./volumes/config/telegraf.d:/etc/telegraf/telegraf.d:ro
    depends_on:
      - influxdb
    networks:
      - default

  influxdb:
    image: influxdb:1.5-alpine
    restart: always
    container_name: ${CONTAINER_NAMESPACE}influxdb
    hostname: influxdb
    environment:
      - VIRTUAL_HOST=${INFLUXDB_HOST}
      - VIRTUAL_PORT=8086
      - LETSENCRYPT_HOST=${INFLUXDB_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./volumes/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./volumes/influxdb:/var/lib/influxdb:rw
    networks:
      default:
        aliases:
         - ${CONTAINER_NAMESPACE}influxdb
      nginx_proxy:

  chronograf:
    image: chronograf:1.4-alpine
    restart: always
    container_name: ${CONTAINER_NAMESPACE}chronograf
    hostname: chronograf
    environment:
      - VIRTUAL_HOST=${CHRONOGRAF_HOST}
      - VIRTUAL_PORT=8888
      - LETSENCRYPT_HOST=${CHRONOGRAF_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - INFLUXDB_URL=http://${CONTAINER_NAMESPACE}influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - KAPACITOR_URL=http://${CONTAINER_NAMESPACE}kapacitor:9092
      - KAPACITOR_USERNAME=${INFLUXDB_ADMIN_USER}
      - KAPACITOR_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - ./volumes/chronograf:/var/lib/chronograf:rw
    depends_on:
      - influxdb
    networks:
      default:
        aliases:
         - ${CONTAINER_NAMESPACE}chronograf
      nginx_proxy:

  kapacitor:
    image: kapacitor:1.4-alpine
    restart: always
    container_name: ${CONTAINER_NAMESPACE}kapacitor
    hostname: kapacitor
    environment:
      - VIRTUAL_HOST=${KAPACITOR_HOST}
      - VIRTUAL_PORT=9092
      - LETSENCRYPT_HOST=${KAPACITOR_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./volumes/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./volumes/kapacitor:/var/lib/kapacitor:rw
    depends_on:
      - influxdb
    networks:
      default:
        aliases:
         - ${CONTAINER_NAMESPACE}kapacitor
      nginx_proxy:

networks:
  nginx_proxy:
    external:
      name: nginxproxy_default
